-- ======================== YEU CAU 1 ================================
-- create table
create table NhanVien (
  MaNV varchar(10) not null primary key,
  HoTen varchar2(150) not null,
  DiaChi varchar2(200) not null,
  DienThoai varchar(11) not null,
  Email varchar(40) not null,
  MaPhong int null,
  ChiNhanh int null,
  Luong float not null );
/
create table PhongBan (
  MaPhong int not null primary key,
  TenPhong varchar2(40) not null,
  TruongPhong varchar(10) not null,
  NgayNhanChuc date not null,
  SoNhanVien int not null,
  ChiNhanh int not null );
/

create table ChiNhanh (
  MaCN int not null primary key, 
  TenCN varchar2(40) not null,
  TruongChiNhanh varchar(10) not null );
/
create table DuAn (
  MaDA int not null primary key,
  TenDA varchar2(40) not null,
  KinhPhi float not null,
  PhongChuTri int not null,
  TruongDA varchar(10) not null );
/
create table PhanCong (
  MaNV varchar(10) not null, 
  DuAn int not null,
  VaiTro varchar2(40) not null,
  PhuCap float not null,
  primary key (MaNV, DuAn) );
/
create table ChiTieu (
  MaChiTieu int not null primary key,
  TenChiTieu varchar2(40) not null,
  SoTien float not null,
  DuAn int not null );
/
-- fk for Phong
-- truong phong / nhan vien
alter table PhongBan 
  add constraint fk_TP_NV foreign key (TruongPhong)
    references NhanVien(MaNV);
-- chi nhanh (phong) / chi nhanh
alter table PhongBan 
  add constraint fk_ChiNhanhPhong_ChiNhanh foreign key (ChiNhanh)
    references ChiNhanh(MaCN);
/
-- fk for du an
-- TruongDA / Nhan Vien
alter table DuAn 
  add constraint fk_TruongDA_NhanVien foreign key (TruongDA)
    references NhanVien(MaNV);
/
-- PhongChiTri / PhongBan
alter table DuAn 
  add constraint fk_PhongChuTri_Phong foreign key (PhongChuTri)
    references PhongBan(MaPhong);
/
-- fk for PhanCong

-- MaNV / NhanVien
alter table PhanCong 
  add constraint fk_MaNVPC_NhanVien foreign key (MaNV)
    references NhanVien(MaNV);
/
-- DuAn / DuAn
alter table PhanCong 
  add constraint fk_DAPC_DuAn foreign key (DuAn)
    references DuAn(MaDA);
/
-- fk for chi nhanh
-- chi nhanh / nhan vien
alter table ChiNhanh 
  add constraint fk_TruongChiNhanh_NV foreign key (TruongChiNhanh)
    references NhanVien(MaNV);
/
-- fk for chi tieu
-- chi tieu / Du An
alter table ChiTieu 
  add constraint fk_DuAnCT_DuAn foreign key (DuAn)
    references DuAn(MaDA);
/
----- drop table and FK -----
/***
alter table NhanVien 
  drop constraint fk_MaPhong_Phong;

alter table NhanVien 
  drop constraint fk_ChiNhanh_ChiNhanh;
  
alter table PhongBan 
  drop constraint fk_TP_NV;
  
alter table PhongBan 
  drop constraint fk_ChiNhanhPhong_ChiNhanh;

alter table DuAn 
  drop constraint fk_TruongDA_NhanVien;

alter table DuAn 
  drop constraint fk_PhongChuTri_Phong;
    
alter table PhanCong 
  drop constraint fk_MaNVPC_NhanVien;

alter table PhanCong 
  drop constraint fk_DAPC_DuAn;

alter table ChiNhanh 
  drop constraint fk_TruongChiNhanh_NV;

alter table ChiTieu 
  drop constraint fk_DuAnCT_DuAn;
  
drop table NhanVien;
drop table DuAn;
drop table ChiTieu;
drop table PhongBan;
drop table PhanCong;
drop table ChiNhanh;

***/
----- end drop table and FK -----


----------------------------------- GENERATE DATE ------------------------------------

--
-- Script was generated by Devart dbForge Data Generator for Oracle, Version 1.0.63.0
-- Product Home Page: http://www.devart.com/dbforge/oracle/data-generator/
-- Script date 5/11/2017 9:26:39 PM
-- Target server version: Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production With the Partitioning, Oracle Label Security, OLAP, Advanced Analytics and Real Application Testing options
-- Target connection string: User Id=admin_bt1;Unicode=True;Connection Timeout=0
--


SET SQLBLANKLINES ON;
SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/SYYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF TZH:TZM';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_NCHAR_CONV_EXCP = FALSE;
ALTER SESSION SET TIME_ZONE = '+07:00';
--
-- Delete data from the table 'ADMIN_BT1.PHANCONG'
--
TRUNCATE TABLE ADMIN_BT1.PHANCONG;
--
-- Delete data from the table 'ADMIN_BT1.CHITIEU'
--
TRUNCATE TABLE ADMIN_BT1.CHITIEU;
--
-- Delete data from the table 'ADMIN_BT1.DUAN'
--
DELETE FROM ADMIN_BT1.DUAN;
--
-- Delete data from the table 'ADMIN_BT1.PHONGBAN'
--
DELETE FROM ADMIN_BT1.PHONGBAN;
--
-- Delete data from the table 'ADMIN_BT1.CHINHANH'
--
DELETE FROM ADMIN_BT1.CHINHANH;
--
-- Delete data from the table 'ADMIN_BT1.NHANVIEN'
--
DELETE FROM ADMIN_BT1.NHANVIEN;

--
-- Inserting data into table ADMIN_BT1.NHANVIEN
--
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV756', 'Robena Drayton', 'Westford', '01638412339', 'MelaniUGoebel255@example.com', 1, 1, 90000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV937', 'Duane Polk', 'Shamrock', '01252774067', 'MeghannLamb599@example.com', 2, 1, 900000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV113', 'Dion Teeter', 'Reading', '01664329954', 'MadelineAbney@example.com', 2, 2, 1000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV483', 'Jammie Manning', 'Matinicus', '01212510799', 'Russell_Heath@nowhere.com', 1, 2, 1000000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV197', 'Caitlin Davies', 'East New Market', '01663272529', 'Mozella.Kline@example.com', 3, 2, 2000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV918', 'Valda Mcneal', 'Millerton', '01259807374', 'ParticiaBratcher27@nowhere.com', 3, 1, 60000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV802', 'Michal Cleveland', 'Fallston', '01669910576', 'Swisher@example.com', 3, 1, 1000000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV769', 'Leigh Shumate', 'Watford', '01259983899', 'Knowles@nowhere.com', 3, 1, 8000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV932', 'Millicent Whitt', 'Foristell', '01216499100', 'Jeremiah_Adcock647@nowhere.com', 1, 2, 1000000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV921', 'Ian Gaines', 'Southend-on-Sea', '09394870175', 'Coreen_AValadez@example.com', 3, 1, 200000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV818', 'Eloise Bedford', 'Falkirk', '01637382511', 'Bustamante6@example.com', 2, 2, 9000000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV631', 'Claude Hamel', 'Rotherham', '01257160779', 'DiaDugger@example.com', 1, 2, 400000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV653', 'Jacquetta Champion', 'Slough', '09399756665', 'Winstead86@example.com', 1, 2, 2000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV601', 'Dominic Berry', 'Cumbernauld', '01214985787', 'Teague@example.com', 3, 2, 6000000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV886', 'Shasta Whiteside', 'Atherstone', '01665080766', 'Guerra4@example.com', 2, 1, 7000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV869', 'Refugia Tibbs', 'St Louis', '01662454612', 'Soria98@nowhere.com', 3, 2, 400000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV245', 'Loida Hardin', 'Newcastle upon Tyne', '01214972560', 'Flood@example.com', 1, 1, 300000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV715', 'Clair Epperson', 'Gloucester', '01255579386', 'dolx2@example.com', 3, 1, 100000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV428', 'Lucien Huerta', 'Pearisburg', '01639308256', 'Lord@nowhere.com', 2, 2, 9000000);
INSERT INTO ADMIN_BT1.NHANVIEN(MANV, HOTEN, DIACHI, DIENTHOAI, EMAIL, MAPHONG, CHINHANH, LUONG) VALUES
('NV794', 'Juan Lewis', 'Clogher', '01669617203', 'Christopher87@example.com', 2, 1, 2000);

--
-- Inserting data into table ADMIN_BT1.CHINHANH
--
INSERT INTO ADMIN_BT1.CHINHANH(MACN, TENCN, TRUONGCHINHANH) VALUES
(1, 'Chi_Nhanh_882', 'NV802');
INSERT INTO ADMIN_BT1.CHINHANH(MACN, TENCN, TRUONGCHINHANH) VALUES
(2, 'Chi_Nhanh_963', 'NV921');
INSERT INTO ADMIN_BT1.CHINHANH(MACN, TENCN, TRUONGCHINHANH) VALUES
(3, 'Chi_Nhanh_317', 'NV794');
INSERT INTO ADMIN_BT1.CHINHANH(MACN, TENCN, TRUONGCHINHANH) VALUES
(4, 'Chi_Nhanh_360', 'NV715');
INSERT INTO ADMIN_BT1.CHINHANH(MACN, TENCN, TRUONGCHINHANH) VALUES
(5, 'Chi_Nhanh_112', 'NV197');
INSERT INTO ADMIN_BT1.CHINHANH(MACN, TENCN, TRUONGCHINHANH) VALUES
(6, 'Chi_Nhanh_068', 'NV869');

--
-- Inserting data into table ADMIN_BT1.PHONGBAN
--
INSERT INTO ADMIN_BT1.PHONGBAN(MAPHONG, TENPHONG, TRUONGPHONG, NGAYNHANCHUC, SONHANVIEN, CHINHANH) VALUES
(1, 'Research and Development', 'NV756', '07/23/2016 07:48:55', 5, 6);
INSERT INTO ADMIN_BT1.PHONGBAN(MAPHONG, TENPHONG, TRUONGPHONG, NGAYNHANCHUC, SONHANVIEN, CHINHANH) VALUES
(2, 'Finance', 'NV937', '01/01/2015 00:15:13', 1, 5);
INSERT INTO ADMIN_BT1.PHONGBAN(MAPHONG, TENPHONG, TRUONGPHONG, NGAYNHANCHUC, SONHANVIEN, CHINHANH) VALUES
(3, 'Executive', 'NV113', '05/04/2016 23:20:22', 2, 3);
INSERT INTO ADMIN_BT1.PHONGBAN(MAPHONG, TENPHONG, TRUONGPHONG, NGAYNHANCHUC, SONHANVIEN, CHINHANH) VALUES
(4, 'Executive', 'NV483', '10/17/2016 22:10:05', 1, 1);
INSERT INTO ADMIN_BT1.PHONGBAN(MAPHONG, TENPHONG, TRUONGPHONG, NGAYNHANCHUC, SONHANVIEN, CHINHANH) VALUES
(5, 'Finance', 'NV197', '04/16/2015 22:09:08', 5, 4);
INSERT INTO ADMIN_BT1.PHONGBAN(MAPHONG, TENPHONG, TRUONGPHONG, NGAYNHANCHUC, SONHANVIEN, CHINHANH) VALUES
(6, 'Sales', 'NV918', '11/26/2015 23:42:32', 1, 2);

--
-- Inserting data into table ADMIN_BT1.DUAN
--
INSERT INTO ADMIN_BT1.DUAN(MADA, TENDA, KINHPHI, PHONGCHUTRI, TRUONGDA) VALUES
(1, 'DuaAn489', 6000, 1, 'NV653');
INSERT INTO ADMIN_BT1.DUAN(MADA, TENDA, KINHPHI, PHONGCHUTRI, TRUONGDA) VALUES
(2, 'DuaAn268', 20000, 2, 'NV937');
INSERT INTO ADMIN_BT1.DUAN(MADA, TENDA, KINHPHI, PHONGCHUTRI, TRUONGDA) VALUES
(3, 'DuaAn196', 3000, 3, 'NV932');
INSERT INTO ADMIN_BT1.DUAN(MADA, TENDA, KINHPHI, PHONGCHUTRI, TRUONGDA) VALUES
(4, 'DuaAn832', 3000, 4, 'NV483');
INSERT INTO ADMIN_BT1.DUAN(MADA, TENDA, KINHPHI, PHONGCHUTRI, TRUONGDA) VALUES
(5, 'DuaAn101', 60000, 5, 'NV802');
INSERT INTO ADMIN_BT1.DUAN(MADA, TENDA, KINHPHI, PHONGCHUTRI, TRUONGDA) VALUES
(6, 'DuaAn739', 3000000, 6, 'NV769');

--
-- Inserting data into table ADMIN_BT1.CHITIEU
--
INSERT INTO ADMIN_BT1.CHITIEU(MACHITIEU, TENCHITIEU, SOTIEN, DUAN) VALUES
(1, 'Chi_Tieu_414', 100000, 1);
INSERT INTO ADMIN_BT1.CHITIEU(MACHITIEU, TENCHITIEU, SOTIEN, DUAN) VALUES
(2, 'Chi_Tieu_624', 90000, 2);
INSERT INTO ADMIN_BT1.CHITIEU(MACHITIEU, TENCHITIEU, SOTIEN, DUAN) VALUES
(3, 'Chi_Tieu_925', 8000000, 3);
INSERT INTO ADMIN_BT1.CHITIEU(MACHITIEU, TENCHITIEU, SOTIEN, DUAN) VALUES
(4, 'Chi_Tieu_908', 2000, 4);
INSERT INTO ADMIN_BT1.CHITIEU(MACHITIEU, TENCHITIEU, SOTIEN, DUAN) VALUES
(5, 'Chi_Tieu_644', 1000, 5);
INSERT INTO ADMIN_BT1.CHITIEU(MACHITIEU, TENCHITIEU, SOTIEN, DUAN) VALUES
(6, 'Chi_Tieu_089', 900000, 6);

--
-- Inserting data into table ADMIN_BT1.PHANCONG
--
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV197', 4, 'Vai_Tro_271', 253);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV937', 2, 'Vai_Tro_448', 36);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV197', 5, 'Vai_Tro_693', 897);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV756', 1, 'Vai_Tro_138', 653);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV483', 4, 'Vai_Tro_717', 405);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV113', 1, 'Vai_Tro_806', 240);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV802', 6, 'Vai_Tro_192', 372);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV918', 5, 'Vai_Tro_314', 865);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV918', 6, 'Vai_Tro_783', 878);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV197', 3, 'Vai_Tro_944', 614);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV113', 3, 'Vai_Tro_008', 407);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV483', 2, 'Vai_Tro_030', 343);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV937', 1, 'Vai_Tro_097', 594);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV483', 3, 'Vai_Tro_605', 728);
INSERT INTO ADMIN_BT1.PHANCONG(MANV, DUAN, VAITRO, PHUCAP) VALUES
('NV113', 2, 'Vai_Tro_735', 562);

COMMIT;

--------------------------- END GENERATE -------------------------------------------
-- fk for nhan vien
-- nhanvien / phong
alter table NhanVien 
  add constraint fk_MaPhong_Phong foreign key (MaPhong)
    references PhongBan(MaPhong);
/
-- nhan vien / chi nhanh
alter table NhanVien 
  add constraint fk_ChiNhanh_ChiNhanh foreign key (ChiNhanh)
    references ChiNhanh(MaCN);
/
-- ======================== END YEU CAU 1 ================================